server:
  port: 8092

spring:
  application:
    name: USER-SERVICE
  zipkin:
    base-url: http://127.0.0.1:9411/

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://host.docker.internal:8088/eureka/,http://host.docker.internal:9099/eureka/
    instance:
      hostname: host.docker.internal
      preferIpAddress: true