#server:
#  port: 8088
#
#eureka:
#  client:
#    register-with-eureka: false
#    fetch-registry: false
#    server:
#      waitTimeInMsWhenSyncEmpty: 0
#
spring:
  application:
    name: Service-Registry
---
spring:
  profiles: zone1
eureka:
  instance:
    metadata-map:
      zone: zone1
    hostname: localhost
  server:
    wait-time-in-ms-when-sync-empty: 0
    eviction-interval-timer-in-ms: 3000
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:9099/eureka/
server:
  port: 8088
---
spring:
  profiles: zone2
eureka:
  instance:
    metadata-map:
      zone: zone2
    hostname: localhost
  server:
    wait-time-in-ms-when-sync-empty: 0
    eviction-interval-timer-in-ms: 3000
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8088/eureka/
server:
  port: 9099
---